/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Atspm Data Api
 * Download Atspm Event Logs and Aggregations
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from 'react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from 'react-query';

import type {
  DeviceEventDownload,
  DeviceEventLoggingConfiguration,
  GetLoggingSyncNewLocationEventsParams,
  ProblemDetails
} from '../data-api.schemas';

import { dataRequest } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary This will kick off the workflow to pull events.
 */
export type getLoggingSyncNewLocationEventsResponse200ApplicationJson = {
  data: DeviceEventDownload[]
  status: 200
}

export type getLoggingSyncNewLocationEventsResponse200TextJson = {
  data: DeviceEventDownload[]
  status: 200
}

export type getLoggingSyncNewLocationEventsResponse406ApplicationJson = {
  data: ProblemDetails
  status: 406
}

export type getLoggingSyncNewLocationEventsResponse406TextJson = {
  data: ProblemDetails
  status: 406
}

export type getLoggingSyncNewLocationEventsResponseSuccess = (getLoggingSyncNewLocationEventsResponse200ApplicationJson | getLoggingSyncNewLocationEventsResponse200TextJson) & {
  headers: Headers;
};
export type getLoggingSyncNewLocationEventsResponseError = (getLoggingSyncNewLocationEventsResponse406ApplicationJson | getLoggingSyncNewLocationEventsResponse406TextJson) & {
  headers: Headers;
};

export type getLoggingSyncNewLocationEventsResponse = (getLoggingSyncNewLocationEventsResponseSuccess | getLoggingSyncNewLocationEventsResponseError)

export const getGetLoggingSyncNewLocationEventsUrl = (params?: GetLoggingSyncNewLocationEventsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/Logging/log?${stringifiedParams}` : `/api/v1/Logging/log`
}

export const getLoggingSyncNewLocationEvents = async (params?: GetLoggingSyncNewLocationEventsParams, options?: RequestInit): Promise<getLoggingSyncNewLocationEventsResponse> => {

  return dataRequest<getLoggingSyncNewLocationEventsResponse>(getGetLoggingSyncNewLocationEventsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetLoggingSyncNewLocationEventsQueryKey = (params?: GetLoggingSyncNewLocationEventsParams,) => {
    return [
    `/api/v1/Logging/log`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetLoggingSyncNewLocationEventsQueryOptions = <TData = Awaited<ReturnType<typeof getLoggingSyncNewLocationEvents>>, TError = ProblemDetails>(params?: GetLoggingSyncNewLocationEventsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getLoggingSyncNewLocationEvents>>, TError, TData>, request?: SecondParameter<typeof dataRequest>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLoggingSyncNewLocationEventsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLoggingSyncNewLocationEvents>>> = ({ signal }) => getLoggingSyncNewLocationEvents(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLoggingSyncNewLocationEvents>>, TError, TData> & { queryKey: QueryKey }
}

export type GetLoggingSyncNewLocationEventsQueryResult = NonNullable<Awaited<ReturnType<typeof getLoggingSyncNewLocationEvents>>>
export type GetLoggingSyncNewLocationEventsQueryError = ProblemDetails


/**
 * @summary This will kick off the workflow to pull events.
 */

export function useGetLoggingSyncNewLocationEvents<TData = Awaited<ReturnType<typeof getLoggingSyncNewLocationEvents>>, TError = ProblemDetails>(
 params?: GetLoggingSyncNewLocationEventsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getLoggingSyncNewLocationEvents>>, TError, TData>, request?: SecondParameter<typeof dataRequest>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetLoggingSyncNewLocationEventsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type getLoggingDeviceEventLoggingResponse200 = {
  data: void
  status: 200
}

export type getLoggingDeviceEventLoggingResponse406ApplicationJson = {
  data: ProblemDetails
  status: 406
}

export type getLoggingDeviceEventLoggingResponse406TextJson = {
  data: ProblemDetails
  status: 406
}

export type getLoggingDeviceEventLoggingResponseSuccess = (getLoggingDeviceEventLoggingResponse200) & {
  headers: Headers;
};
export type getLoggingDeviceEventLoggingResponseError = (getLoggingDeviceEventLoggingResponse406ApplicationJson | getLoggingDeviceEventLoggingResponse406TextJson) & {
  headers: Headers;
};

export type getLoggingDeviceEventLoggingResponse = (getLoggingDeviceEventLoggingResponseSuccess | getLoggingDeviceEventLoggingResponseError)

export const getGetLoggingDeviceEventLoggingUrl = () => {




  return `/api/v1/Logging/deviceEventLoggin`
}

export const getLoggingDeviceEventLogging = async (deviceEventLoggingConfiguration: DeviceEventLoggingConfiguration, options?: RequestInit): Promise<getLoggingDeviceEventLoggingResponse> => {

  return dataRequest<getLoggingDeviceEventLoggingResponse>(getGetLoggingDeviceEventLoggingUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json-patch+json', ...options?.headers },
    body: JSON.stringify(
      deviceEventLoggingConfiguration,)
  }
);}




export const getGetLoggingDeviceEventLoggingMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getLoggingDeviceEventLogging>>, TError,{data: DeviceEventLoggingConfiguration}, TContext>, request?: SecondParameter<typeof dataRequest>}
): UseMutationOptions<Awaited<ReturnType<typeof getLoggingDeviceEventLogging>>, TError,{data: DeviceEventLoggingConfiguration}, TContext> => {

const mutationKey = ['getLoggingDeviceEventLogging'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getLoggingDeviceEventLogging>>, {data: DeviceEventLoggingConfiguration}> = (props) => {
          const {data} = props ?? {};

          return  getLoggingDeviceEventLogging(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetLoggingDeviceEventLoggingMutationResult = NonNullable<Awaited<ReturnType<typeof getLoggingDeviceEventLogging>>>
    export type GetLoggingDeviceEventLoggingMutationBody = DeviceEventLoggingConfiguration
    export type GetLoggingDeviceEventLoggingMutationError = ProblemDetails

    export const useGetLoggingDeviceEventLogging = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getLoggingDeviceEventLogging>>, TError,{data: DeviceEventLoggingConfiguration}, TContext>, request?: SecondParameter<typeof dataRequest>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof getLoggingDeviceEventLogging>>,
        TError,
        {data: DeviceEventLoggingConfiguration},
        TContext
      > => {
      return useMutation(getGetLoggingDeviceEventLoggingMutationOptions(options));
    }
