name: Build Containers

on:
  push:
    branches:
      - Staging

permissions:
  id-token: write
  contents: read

jobs:
  changes:
    name: Find Containers to build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4     
      # Check which Containers have changed files
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: .github/filters.json
    outputs:
      changes: ${{steps.changes.outputs.changes}}

  build:
    name: Build Job
    needs: changes
    if: ${{ needs.changes.outputs.changes != '[]'}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        name: ${{fromJson(needs.changes.outputs.changes)}}

    steps:
      - name: ⬇️ Set up code
        uses: actions/checkout@v4

      - name: 📁 Get Working Dir
        run: |
          docker_dir="$(cat .github/filters.json | jq '."${{matrix.name}}"' | tr -d '**\n"')"
          echo DOCKERFILE_DIR=${docker_dir} >> $GITHUB_ENV

      - name: 🗝️ Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: 🐳 Set up Docker Buildx
        id: builder
        uses: docker/setup-buildx-action@v3

      - name: 🗝️ Authenticate Docker to Google Cloud
        run: |
          gcloud auth configure-docker "us-docker.pkg.dev"

      - name: 🏷️ Extract tags from GitHub
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.GCP_ARTIFACT_REPO }}/${{ matrix.name }}
          tags: |
            type=sha

      - name: 📦 Build and push image
        uses: docker/build-push-action@v6
        if: ${{ matrix.name != 'atspmwebsite'}}
        with:
          builder: ${{ steps.builder.outputs.name }}
          tags: ${{ steps.meta.outputs.tags }}
          context: Atspm/
          file: ${{ env.DOCKERFILE_DIR }}/Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: 📦 Build and push image WebUI
        uses: docker/build-push-action@v6
        if: ${{ matrix.name == 'atspmwebsite'}}
        with:
          builder: ${{ steps.builder.outputs.name }}
          tags: ${{ steps.meta.outputs.tags }}
          context: ${{ env.DOCKERFILE_DIR }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: 🚀 Set Service Name and Region from JSON
        id: service_and_region
        run: |
          # Load the service name from the JSON file based on the matrix name
          service_name=$(jq -r --arg matrix_name "${{ matrix.name }}" '.[$matrix_name]' .github/service-names.json)
          echo "SERVICE_NAME=$service_name" >> $GITHUB_ENV

      - name: 🚀 Deploy to Cloud Run
        if: ${{ success() }}
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ env.SERVICE_NAME }}  # Use the service name from the previous step
          image: ${{ steps.meta.outputs.tags }}
          region: ${{ secrets.GCP_REGION }}  # Use the region from the previous step
          platform: managed
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
