name: Publish NuGet Packages

on:
  release:
    types: [published, prereleased]

jobs:
  nuget:
    name: Pack and Publish NuGet
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 🧰 Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # adjust based on your projects

      - name: 🏷️ Extract Version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: 📦 Build & Pack
        run: |
          dotnet build Atspm/Atspm.csproj -c Release
          dotnet build Atspm.Infrastructure/Atspm.Infrastructure.csproj -c Release
          dotnet pack Atspm/Atspm.csproj -c Release -o out /p:PackageVersion=${{ env.VERSION }}
          dotnet pack Atspm.Infrastructure/Atspm.Infrastructure.csproj -c Release -o out /p:PackageVersion=${{ env.VERSION }}

      - name: 🚀 Publish to NuGet
        run: |
          dotnet nuget push "out/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
